name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node env
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the app
      - name: Build
        env:
          VITE_BASE_PATH: ${{ secrets.VITE_BASE_PATH }}
        run: yarn build
      
      - name: Testing secrets
        run: echo ${{ secrets.VITE_BASE_PATH }}
        

      # Deploy contents of 'dist' folder to GitHub Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          


